config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :user_songs
  resources :users
  resources :songs
  resources :genres
  root "songs#index"
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user_song.rb
class UserSong < ApplicationRecord
  belongs_to :user
  belongs_to :song
end

app/controllers/user_songs_controller.rb
class UserSongsController < ApplicationController
  before_action :set_user_song, only: [:show, :edit, :update, :destroy]

  # GET /user_songs
  # GET /user_songs.json
  def index
    @user_songs = UserSong.all
  end

  # GET /user_songs/1
  # GET /user_songs/1.json
  def show
  end

  # GET /user_songs/new
  def new
    @user_song = UserSong.new
  end

  # GET /user_songs/1/edit
  def edit
  end

  # POST /user_songs
  # POST /user_songs.json
  def create
    @user_song = UserSong.new(user_song_params)

    respond_to do |format|
      if @user_song.save
        format.html { redirect_to @user_song, notice: 'User song was successfully created.' }
        format.json { render :show, status: :created, location: @user_song }
      else
        format.html { render :new }
        format.json { render json: @user_song.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_songs/1
  # PATCH/PUT /user_songs/1.json
  def update
    respond_to do |format|
      if @user_song.update(user_song_params)
        format.html { redirect_to @user_song, notice: 'User song was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_song }
      else
        format.html { render :edit }
        format.json { render json: @user_song.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_songs/1
  # DELETE /user_songs/1.json
  def destroy
    @user_song.destroy
    respond_to do |format|
      format.html { redirect_to user_songs_url, notice: 'User song was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_song
      @user_song = UserSong.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_song_params
      params.require(:user_song).permit(:position, :user_id, :songs_id)
    end
end

app/helpers/user_songs_helper.rb
module UserSongsHelper
end

app/views/user_songs/_form.html.erb
<%= form_for(user_song) do |f| %>
  <% if user_song.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user_song.errors.count, "error") %> prohibited this user_song from being saved:</h2>

      <ul>
      <% user_song.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :position %>
    <%= f.number_field :position %>
  </div>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.text_field :user_id %>
  </div>

  <div class="field">
    <%= f.label :songs_id %>
    <%= f.text_field :songs_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/user_songs/edit.html.erb
<h1>Editing User Song</h1>

<%= render 'form', user_song: @user_song %>

<%= link_to 'Show', @user_song %> |
<%= link_to 'Back', user_songs_path %>

app/views/user_songs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>User Songs</h1>

<table>
  <thead>
    <tr>
      <th>Position</th>
      <th>User</th>
      <th>Songs</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_songs.each do |user_song| %>
      <tr>
        <td><%= user_song.position %></td>
        <td><%= user_song.user %></td>
        <td><%= user_song.songs %></td>
        <td><%= link_to 'Show', user_song %></td>
        <td><%= link_to 'Edit', edit_user_song_path(user_song) %></td>
        <td><%= link_to 'Destroy', user_song, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User Song', new_user_song_path %>

app/views/user_songs/new.html.erb
<h1>New User Song</h1>

<%= render 'form', user_song: @user_song %>

<%= link_to 'Back', user_songs_path %>

app/views/user_songs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Position:</strong>
  <%= @user_song.position %>
</p>

<p>
  <strong>User:</strong>
  <%= @user_song.user %>
</p>

<p>
  <strong>Songs:</strong>
  <%= @user_song.songs %>
</p>

<%= link_to 'Edit', edit_user_song_path(@user_song) %> |
<%= link_to 'Back', user_songs_path %>